easy_admin:
   entities:
       Category :
          class: App\Entity\Categorie
          label: 'Catégories'
          list:
              actions:
                  - { name: 'deleteFromList', type: 'method', label: '' }
                  - { name: '-delete' }
              sort: ['libelle', 'ASC']
              title: "Liste des %%entity_label%%"
              fields:
                  - { property: 'libelle', label: 'Titre' }
                  - { property: 'produits', label: "Articles liée" }
          search:
            fields: ['libelle']